config/routes.rb
Rails.application.routes.draw do

  root "recipes#index"

  resources :recipes

  resources :users
  get "signup" => "users#new"

  resource :session, only: [:new, :create, :destroy]
  get "signin" => "sessions#new"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/ingredient.rb
# == Schema Information
#
# Table name: ingredients
#
#  id         :bigint           not null, primary key
#  name       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  recipe_id  :bigint           not null
#
class Ingredient < ApplicationRecord
  belongs_to :ingredient
end

app/models/like.rb
# == Schema Information
#
# Table name: likes
#
#  id                  :bigint           not null, primary key
#  recipe_box_items_id :bigint           not null
#  user_id             :bigint           not null
#  created_at          :datetime         not null
#  updated_at          :datetime         not null
#
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :recipe_box_items, counter_cache: true
end

app/models/recipe.rb
# == Schema Information
#
# Table name: recipes
#
#  id          :bigint           not null, primary key
#  name        :string
#  category    :string
#  description :text
#  image       :string
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  user_id     :bigint           not null
#
class Recipe < ApplicationRecord
  has_many :recipe_box_items
end

app/models/recipe_box_item.rb
# == Schema Information
#
# Table name: recipe_box_items
#
#  id         :bigint           not null, primary key
#  recipe_id  :bigint           not null
#  user_id    :bigint           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class RecipeBoxItem < ApplicationRecord
  belongs_to :recipe
  belongs_to :user
  has_many :likes, dependent: :destroy
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :bigint           not null, primary key
#  username        :string
#  password_digest :string
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#
class User < ApplicationRecord
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  private

  def require_signin
    unless signed_in?
      session[:intended_url] = request.url
      redirect_to signin_url
    end
  end

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :current_user

  def signed_in?
    !current_user.nil?
  end

  helper_method :signed_in?

  def current_user?(user)
    current_user == user
  end

  helper_method :current_user?
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController

  def index
    @recipes = Recipe.all
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(username: params[:username])

    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to session[:intended_url] || user
      session[:intended_url] = nil
    else
      flash.now[:alert] = "Invalid email/password combination!"
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_signin, except: %i[new create]
  before_action :require_correct_user, only: %i[edit update destroy]

  def index
    @users = User.order(created_at: :desc)
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      session[:user_id] = @user.id
      redirect_to @user
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to @user, notice: "Account successfully updated!"
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @user.destroy
    session[:user_id] = nil
    redirect_to root_url, alert: "Account successfully deleted!"
  end

private

  def user_params
    params.require(:user).permit(:username, :password, :password_confirmation)
  end

  def require_correct_user
    @user = User.find(params[:id])
    redirect_to root_url unless current_user?(@user)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def nav_link_to(text, url, options={})
    link_to(text, url, options.merge(class: url))
  end

  def nav_link_class(url)
    page_active?(url) ? "active" : ""
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/layouts/_header.html.erb
<header>
  <nav class="primary">
    <ul>
      <% if signed_in? %>
        <li>
          <%= nav_link_to current_user.username, current_user %>
        </li>
        <li>
          <%= button_to "Sign Out", session_path, method: :delete %>
        </li>
      <% else %>
        <li>
          <%= nav_link_to "Sign In", signin_path %>
        </li>
        <li>
          <%= nav_link_to "Sign Up", signup_path %>
        </li>
      <% end %>
    </ul>
  </nav>

  <div class="logo">
    <%= link_to root_path do %>
      <%# <%= image_tag("logo.svg") %>
      <h1>RecipeNut 🥜</h1>
    <% end %>
  </div>

  
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RecipeNut</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application.tailwind.css", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>

  </head>

  <body>
    <p class="notice"><%= notice %></p> 
    <p class="alert"><%= alert %></p> 
    <%= render "layouts/header" %>

    <%= yield %>
  </body>
</html>

app/views/recipes/_recipe.html.erb
<div class="recipe">
  <%= link_to image_tag(recipe.image), recipe %>
  <div class="name">
    <%= link_to recipe.name, recipe %>
  </div>
  <div class="category">
    <%= recipe.category %>
  </div>

</div>

app/views/recipes/index.html.erb
Hello, Recipe Nut :peanut:

<div class="recipes">
  <%= render @recipes %>
</div>

app/views/users/_form.html.erb
<%= form_with(model: @user) do |f| %>
  <%= f.label :username %>
  <%= f.text_field :username %>

  <%= f.label :password, 'Password' %>
  <%= f.password_field :password %>

  <%= f.label :password_confirmation, 'Confirm Password' %>
  <%= f.password_field :password_confirmation %>

  <% if @user.new_record? %>
    <%= f.submit 'Create Account' %>
  <% else %>
    <%= f.submit 'Update Account' %>
  <% end %>
<% end %>

app/views/users/new.html.erb
<h2>Sign Up</h2>
<%= render "form", user: @user %>